version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      APACHE_SERVER_NAME: obs
      APPLICATION_ENV: development
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "remote_host=host.docker.internal"

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: obs
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
